# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "cloud.google.com/go";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/gocloud";
      rev = "310d83b78255a1605c3bd3a9ffe1606cf09ebcac";
      sha256 = "1p6gclpxanlyixmlk2yjmw6vp70jh46vg14h6vm24lhgbdlkn8ib";
    };
  }
  {
    goPackagePath = "github.com/golang/groupcache";
    fetch = {
      type = "git";
      url = "https://github.com/golang/groupcache";
      rev = "8c9f03a8e57eb486e42badaed3fb287da51807ba";
      sha256 = "0vjjr79r32icjzlb05wn02k59av7jx0rn1jijml8r4whlg7dnkfh";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "fa093f59480c0adaaabf88a72a0b0e48b95aec25";
      sha256 = "0v23s5n33505pdb7wz7s7fjc9i2i8r0x2pavk026kfz9gr7dlyrf";
    };
  }
  {
    goPackagePath = "github.com/googleapis/gax-go";
    fetch = {
      type = "git";
      url = "https://github.com/googleapis/gax-go";
      rev = "be11bb253a768098254dc71e95d1a81ced778de3";
      sha256 = "072iv8llzr99za4pndfskgndq9rzms38r0sqy4d127ijnzmgl5nd";
    };
  }
  {
    goPackagePath = "github.com/sirupsen/logrus";
    fetch = {
      type = "git";
      url = "https://github.com/sirupsen/logrus";
      rev = "e8e563a8238de839b9cbbc1d9807d140a5a24a8d";
      sha256 = "1xgvwma9j6gzf5jgww6ps1yxyhvifzy65830y6k4az6yza5c2vfw";
    };
  }
  {
    goPackagePath = "go.opencensus.io";
    fetch = {
      type = "git";
      url = "https://github.com/census-instrumentation/opencensus-go";
      rev = "46dfec7deb6e8c5d4a46f355c0da7c6d6dc59ba4";
      sha256 = "1d4d381vw0rqmb27iyg5l8nn66rr6yzn8mk1phyrkx1a6b2fsxww";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "e0ff5e5a1de5b859e2d48a2830d7933b3ab5b75f";
      sha256 = "1kyf5ydfcfks64j3xxh2zbrshfr2cyzyk6i7l3a79hvkksyipjs0";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "bf48bf16ab8d622ce64ec6ce98d2c98f916b6303";
      sha256 = "1sirdib60zwmh93kf9qrx51r8544k1p9rs5mk0797wibz3m4mrdg";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "10377860bb8e8e259ba97296f3b7656772f975bc";
      sha256 = "179pwyznxagk80hw9pz1s77ja1flmjl399718jvbnzp1jfd1fsgb";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "afb9336c4530b4b18f37130eab53f245f7d6821e";
      sha256 = "14m35z8iswa7x3md75h2z0fvqpjf0bhidmbmc642k57m4qi6zn8r";
    };
  }
  {
    goPackagePath = "gonum.org/v1/gonum";
    fetch = {
      type = "git";
      url = "https://github.com/gonum/gonum";
      rev = "015024673d2bbd05971e5baac93843f2c180e792";
      sha256 = "1ys16gkbmqb2z1bjj5vl8grgzpzg7liwc6zk1pjzh9345ljglx56";
    };
  }
  {
    goPackagePath = "google.golang.org/api";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/google-api-go-client";
      rev = "ac9be1f8f530b062691cca7d1e7c474accbc3b90";
      sha256 = "0jmz8lxvjvl7vk2i4bw1484415gk3i8bj3pjvh4y8ppsb90ksqg1";
    };
  }
  {
    goPackagePath = "google.golang.org/genproto";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-genproto";
      rev = "b979b6f78d84775ef7a93ffc8034924947960f29";
      sha256 = "0d07zm9hp7j3ycwahxiipqvdvaqb114akyif1vx3xkz9258y0z15";
    };
  }
  {
    goPackagePath = "google.golang.org/grpc";
    fetch = {
      type = "git";
      url = "https://github.com/grpc/grpc-go";
      rev = "a906ca0441ceb1f7cd4f5c7de30b8e81ce2ff5e8";
      sha256 = "1ig1pas14ydp3whb3xa798s07am1y5cr009f020r9f4dy56r3qyw";
    };
  }
  {
    goPackagePath = "google.golang.org/protobuf";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/protobuf";
      rev = "3ebaa92e92fa8b5e8a8b1c78a4a439cd89c7c8af";
      sha256 = "0gfnqh3kl6n0zprxbwqwvx8xcn5jhfk8zwibw0wxfj7m9b02fhqs";
    };
  }
]
